### ISSUE TITLE
Send header & form parameters via REST API

### ISSUE THREAD

**Issue by neilharia7** [optimajet/WorkflowServer#11]
Hi, is it possible to send multiple parameters in urlencoded format as well as in the headers?

**Comment by optimajet** [comment]
Hi. Yes, it is possible, you can use the JSON array with parameters in the URL. Like here:
http://localhost:8077/workflowapi/createinstance/f19dc004-401d-d684-5041-405cd4473f15?schemeCode=simple&parameters=[{%22persist%22:true,%22name%22:%22parameter1%22,%22value%22:%2242%22}]
