### ISSUE TITLE
Caught a callback exception

### ISSUE THREAD

**Issue by jibijohndavid** [optimajet/WorkflowServer#7]
We have integrated workflow server and callback api into our project. When we did a load test (20 to 50 Request in 2 to 3 seconds) for the application the workflow server gets stopped continuously. We have hosted workflow server as windows service and callback api as console app. Some times callback APi also stop accepting requests.
The following error is what we got from the Workflow server:

{"@t":"2019-10-03T14:33:26.4608463Z","@mt":"Caught a callback  exception","@l":"Error","ExceptionInfo":{"Exeptions":"(CallbackException)Code:  NoContent","Message":"Code: NoContent","StackTrace":" at  OptimaJet.WorkflowServer.CallbackProvider.GetIdentities(ProcessInstance  processInstance, WorkflowRuntime runtime, String ruleName, String parameter)\r\n  at  OptimaJet.Workflow.Core.Runtime.AggregatingRuleProvider.GetIdentities(ProcessInstance  processInstance, WorkflowRuntime runtime, String ruleName, String parameter)\r\n  at OptimaJet.Workflow.Core.Runtime.WorkflowRuntime.GetIdentities(ProcessInstance  processInstance, String ruleName, String parameter)\r\n at  OptimaJet.Workflow.Core.Runtime.WorkflowRuntime.GetActors(ProcessInstance  processInstance, TransitionDefinition transition)\r\n at  OptimaJet.Workflow.Core.Runtime.WorkflowRuntime.GetAllActorsForCommandTransitions(ProcessInstance  processInstance, ActivityDefinition selectedActivity, List`1 classifiers, List`1  transitionsToExclude)\r\n at  OptimaJet.Workflow.Core.Runtime.WorkflowRuntime.GetAllActorsForCommandTransitionsInternal(ProcessInstance  processInstance, List`1 classifiers, Boolean beginningWithRoot, String  activityName)\r\n at  OptimaJet.Workflow.Core.Runtime.WorkflowRuntime.<>c__DisplayClass214_0.<GetAllActorsForDirectCommandTransitionsAsync>b__0()\r\n  at  OptimaJet.Workflow.Core.Runtime.WorkflowRuntime.<GetAllActorsForDirectCommandTransitionsAsync>d__214.MoveNext()\r\n  at  OptimaJet.WorkflowServer.DatabaseOperations.<FillInboxAsync>d__74.MoveNext()\r\n  at  OptimaJet.WorkflowServer.WorkflowServerRuntime.<FillInboxAsync>d__35.MoveNext()\r\n  at OptimaJet.WorkflowServer.Extensions.<FireAndForget>d__1.MoveNext()"}}
--

The error returned from callback api is attached.
![WFCallBackError](https://user-images.githubusercontent.com/25331085/66137970-83211680-e61b-11e9-9109-60df4b4241ec.PNG)

**Comment by optimajet** [comment]
Dear Jibi.

Share PERuleProvider.cs file from your project.

**Comment by jibijohndavid** [comment]
using API.Common.Generics;
using Hangfire;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using WF.CallbackAPI.Constants;
using WF.CallbackAPI.Enums;
using WF.CallbackAPI.Helpers;
using WF.CallbackAPI.Helpers.HttpClient;
using WF.CallbackAPI.Models;





namespace WF.CallbackAPI.WorkflowObjects
{
    //Rule provider for Police Eye
    public partial class RuleProvider
    {
        //Manager
        public IEnumerable<string> PESecretaryRuleGet(ProcessInfo processInstance, string parameter)
        {
            return new List<string>();
        }


        /// <summary>
        ///  commented for approval
        /// </summary>
        /// <param name="processInstance"></param>
        /// <param name="runtime"></param>
        /// <param name="identityId"></param>
        /// <param name="parameter"></param>
        /// <returns></returns>
        public bool PESecretaryRuleCheck(ProcessInfo processInstance, string identityId,
            string parameter)
        {
            //IDbDataParameter[] sqlParameters =
            //{
            //    new SqlParameter("@ProcessId", processInstance.Id),
            //    new SqlParameter("@AssignedTo", "12345")
            //};
            //_dbSqlHelper.ExecuteNonQueryAsync("[WEB].[SHJSP_SetPoliceEyeAssignedTo]", sqlParameters).ConfigureAwait(false);
            Envelope<bool> result = HttpClientHelper.GetAsync<bool>("v1/police-eye/assign-request-to-secretary?ProcessId=" + processInstance.Id, null).Result;
            if (result.Data != null)
            {
                return result.Success;
            }
            return false;
        }

        //HR
        public IEnumerable<string> PEStaffRuleGet(ProcessInfo processInstance, string parameter)
        {
            return new List<string>();
        }

        /// <summary>
        ///  Submission
        /// </summary>
        /// <param name="processInstance"></param>
        /// <param name="runtime"></param>
        /// <param name="identityId"></param>
        /// <param name="parameter"></param>
        /// <returns></returns>
        public bool PEStaffRuleCheck(ProcessInfo processInstance, string identityId,
            string parameter)
        {
            Envelope<bool> result = HttpClientHelper.GetAsync<bool>("v1/police-eye/assign-request-level-one-to-user?ProcessId="+processInstance.Id, null).Result;
            if(result.Data != null)
            {
                return result.Success;
            }
            return false;          
        }
    }
}

**Comment by optimajet** [comment]
I suppose result is null in PEStaffRuleCheck method.

Do you have a license or support plan?
I'm not sure that such performance tests are relevant for the trial version.

**Comment by jibijohndavid** [comment]
Yes I have licence.

**Comment by optimajet** [comment]
I see the issue is caused by your code in PERuleProvider.cs. It's not a bug.
If you need extra help, please, send a request to support@optimajet.com.
