### ISSUE TITLE
WorkflowServer Callback API's examples

### ISSUE THREAD

**Issue by hem19** [optimajet/WorkflowServer#8]
I'm trying to work with WorkflowServer by giving Callback API's for different operations. I am able to work out with Get methods but not able to work out API with Post actions. 

1. I have written custom WebAPI for getting list of conditions from server, pasted the URL under "Getting a list of conditions" URL box, clicked on "Test" and it's working fine, turned the button green.
2. I have written another custom WebAPI for execution of the condition. I need to pass some parameters to this WebAPI. I'm not sure if that's do-able or not, but seeing the swagger file it seems possible. 

I think that's exactly the use case of deploying WorkflowServer separately so that we can write our own API to be called. I didn't find any such example. Could you point me out to any such example?

**Comment by optimajet** [comment]
Workflow Server Callback API example .NET - https://github.com/optimajet/workflow-server-callback-api-example
