### ISSUE TITLE
Error from getformbyflow Workflow api method for roles other than "Any Role"

### ISSUE THREAD

**Issue by ja8669181** [optimajet/WorkflowServer#9]
I am trying to use the Business flow section. I used the RoleBased example with callback Api sample at https://codesandbox.io/s/workflowservercallbackapi-57zb8. The steps are as below

1. Created 4 dummy forms Default, User, Manager, and Accountant
2. Created a business flow named Rolebased
![image](https://user-images.githubusercontent.com/66100918/83214180-8c9a5880-a181-11ea-8c4a-6f42de9d027a.png)
3. Run the getformbyflow api method
![image](https://user-images.githubusercontent.com/66100918/83214411-27933280-a182-11ea-8d95-077cef7ec35d.png)
And it shows an error rule with User is not implemented("One or more errors occurred. (Rule with name User is not implemented). InnerException: Rule with name User is not implemented"). My workflow is at state Draft. My doubt is why is it looking for rule named User. Shouldn't it use checkrole rule against the actor "User" to identify the find the form. 
4. Now if I change the Role in business flow to "Any Roles" it works

Also if I am wrong please help me in creating the User rule

**Comment by optimajet** [comment]
Fixed in WFS 2.6 https://workflowengine.io/downloads/server/
